In [3]:
from gym import make
from network import Model
import torch
import torch.nn as nn

In [4]:
env = make("LunarLander-v2")

In [5]:
state = env.reset()

In [6]:
transition = env.step(1)

In [7]:
env.action_space

Discrete(4)

In [8]:
state_tensor = torch.FloatTensor(state)

In [9]:
model = nn.Sequential(
    nn.Linear(8, 16),
    nn.Sigmoid(),
    nn.Linear(16, 16),
    nn.Sigmoid(),
    nn.Linear(16, 4),
        )

In [10]:
model(state_tensor)

tensor([-0.1654, -0.1887, -0.0592,  0.3539], grad_fn=<AddBackward0>)

In [11]:
model = Model(8, 4)

In [12]:
model(state_tensor)

tensor([ 0.0389, -0.2024, -0.5541, -0.1134], grad_fn=<AddBackward0>)

In [13]:
from train import DQN

In [14]:
dqn = DQN(8, 4)

In [15]:
dqn.memory

deque([])

In [16]:
for _ in range(20):
    dqn.consume_transition(transition)

In [17]:
batch = dqn.sample_batch()

In [23]:
states = batch

In [21]:
from train import Transition

In [24]:
batch = Transition(*zip(*states))

In [35]:
torch.Tensor(batch.action)

tensor([-0.3374, -0.3374, -0.3374, -0.3374, -0.3374, -0.3374, -0.3374, -0.3374,
        -0.3374, -0.3374])

In [46]:
a = dqn.model(torch.FloatTensor(batch.state))[0].argmax()

NotImplementedError: Could not run 'aten::values' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::values' is only available for these backends: [SparseCPU, SparseCsrCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

SparseCPU: registered at /pytorch/build/aten/src/ATen/RegisterSparseCPU.cpp:959 [kernel]
SparseCsrCPU: registered at /pytorch/build/aten/src/ATen/RegisterSparseCsrCPU.cpp:200 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: registered at /pytorch/torch/csrc/autograd/generated/ADInplaceOrViewType_0.cpp:2322 [kernel]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradMLC: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradHPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:10105 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_1.cpp:10518 [kernel]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:255 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


In [29]:
torch.Tensor()

TypeError: new() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray), but expected one of:
 * (*, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [106]:
dqn.model(torch.FloatTensor(dqn.sample_batch()))

/mnt/c/Homeworks/MADE-Practical-RL-homework-2021/hw01_lunar_lander/train.py:42: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(batch)


TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [110]:
a = deque()

In [113]:
a.append(transition[:2])

In [117]:
sample(a, 3)

[(array([-0.06280918,  1.3024409 , -0.72931874, -0.6433341 ,  0.12079125,
          0.339049  ,  0.        ,  0.        ], dtype=float32),
  -2.660535036773068),
 (array([-0.06280918,  1.3024409 , -0.72931874, -0.6433341 ,  0.12079125,
          0.339049  ,  0.        ,  0.        ], dtype=float32),
  -2.660535036773068),
 (array([-0.06280918,  1.3024409 , -0.72931874, -0.6433341 ,  0.12079125,
          0.339049  ,  0.        ,  0.        ], dtype=float32),
  -2.660535036773068)]