In [29]:
from gym import make
from network import Model
import torch
import torch.nn as nn

In [2]:
env = make("LunarLander-v2")

In [3]:
state = env.reset()

In [4]:
state

array([-3.5333633e-04,  1.4222295e+00, -3.5799675e-02,  5.0263906e-01,
        4.1617962e-04,  8.1091421e-03,  0.0000000e+00,  0.0000000e+00],
      dtype=float32)

In [5]:
env.action_space

Discrete(4)

In [12]:
state_tensor = torch.FloatTensor(state)

In [26]:
model = nn.Sequential(
    nn.Linear(8, 16),
    nn.Sigmoid(),
    nn.Linear(16, 16),
    nn.Sigmoid(),
    nn.Linear(16, 4),
        )

In [27]:
model(state_tensor)

tensor([0.8142, 0.5177, 0.1555, 0.1561], grad_fn=<AddBackward0>)

In [30]:
model = Model()

In [31]:
model(state_tensor)

tensor([-0.1865,  0.3213,  0.3480,  0.4848], grad_fn=<AddBackward0>)